GET http://localhost:8000/orders?limit=f
Accept: application/json

###
GET http://localhost:8000/orders?offset=4
Accept: application/json

###
GET http://localhost:8000/orders?limit=4
Accept: application/json

###
GET http://localhost:8000/orders?limit=0
Accept: application/json

###
GET http://localhost:8000/orders
Accept: application/json

###
GET http://localhost:8000/orders?limit=0&offset=e
Accept: application/json

###
GET http://localhost:8000/orders?limit=0&offset=0
Accept: application/json


###
#GET http://localhost:8000/couriers/meta-info/1?startDate=2023-01-20&endDate=2023-01-21
#Accept: application/json
#
####
#GET http://localhost:8000/couriers/meta-info/1?startDate=2023-01-20&endDate=2024-01-21
#Content-Type: application/json
#
#{}
#
####
#POST http://localhost:8000/orders/complete
#Content-Type: application/json
#
#{
#  "complete_info": [
#    {
#      "courier_id": 1,
#      "order_id": 5,
#      "complete_time": "2024-01-06T18:31:20.477Z"
#    },
#    {
#      "courier_id": 1,
#      "order_id": 7,
#      "complete_time": "2024-01-06T18:31:20.477Z"
#    }
#  ]
#}

###
